on:
  workflow_dispatch:
jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: test command
        run: |
          id -a
          sudo systemctl start nginx
          sudo systemctl start mysql
          sudo systemctl status nginx
          sudo systemctl status mysql
